SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `sys_user`;
CREATE TABLE `sys_user` (
  `USER_ID` char(32) NOT NULL,
  `USER_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `PASSWORD_SALT` varchar(255) NOT NULL,
  `GENDER` enum('male','female','secret') DEFAULT 'secret',
  `CREATE_TIME` datetime NOT NULL ON UPDATE CURRENT_TIMESTAMP,
  `LAST_UPDATE_TIME` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `IDX_USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS `sys_role`;
CREATE TABLE `sys_role` (
  `ROLE_ID` char(32) NOT NULL,
  `ROLE_NAME` varchar(40) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`),
  UNIQUE KEY `IDX_ROLE_NAME` (`ROLE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;